# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-06 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d')),
                ('source', models.CharField(blank=True, max_length=40, verbose_name='Quote Reference')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Quotes',
                'verbose_name': 'Quote',
            },
        ),
    ]
