# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='image',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d'),
        ),
    ]
