# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 14:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20, verbose_name='City/Town/Village')),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='states.Country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='states.State')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss', 'Miss'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('Alhaji', 'Alhaji'), ('Chief', 'Chief'), ('Prince', 'Prince'), ('Princess', 'Princess')], max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d')),
                ('age_range', models.CharField(choices=[('25-30', '25-30 years'), ('31-35', '31-35 years'), ('36-40', '36-40 years'), ('41-50', '41-50 years'), ('51-60', '51-60 years'), ('60+', '60+ years')], max_length=5)),
                ('availability', models.CharField(choices=[('daily', 'Daily'), ('forth-nightly', 'Forth-nightly'), ('monthly', 'Monthly')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=13)),
                ('type_to_handle', models.CharField(choices=[('project-based', 'Project-based Jobs'), ('long-term', 'Long-term Jobs'), ('one-off', 'One-off Jobs')], max_length=20)),
                ('short_biography', models.TextField(blank=True)),
                ('cv_file', models.FileField(upload_to='uploads/%Y/%m/%d', verbose_name='Attach PDF copy of CV ')),
                ('slug', models.SlugField(unique=True)),
                ('linkedin_url', models.URLField(blank=True, verbose_name='Link to LinkedIn Bio/profile')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingExpert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('name_of_business', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('N', 'New User'), ('R', 'Returning User')], max_length=1)),
                ('about_project', models.CharField(max_length=100, verbose_name='What is your project about?')),
                ('skills_required', models.CharField(max_length=100, verbose_name='What skills are required?')),
                ('project_description', models.TextField(verbose_name='Describe your project')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d', verbose_name='Upload files that could be useful')),
                ('proposed_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_date', models.DateTimeField(verbose_name='Expected delivery date')),
                ('further_follow_up', models.CharField(max_length=12, verbose_name='Who do we contact for further follow up?')),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('address_of_business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='expert.Address')),
                ('sector_or_industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert.Industry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting With Expert',
                'ordering': ('name',),
                'verbose_name_plural': 'Meetings With Expert',
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_diagnostics', models.BooleanField(default=False)),
                ('operation_optimization', models.BooleanField(default=False)),
                ('traning_needs', models.BooleanField(default=False, verbose_name='Training/HR needs')),
                ('business_plan', models.BooleanField(default=False, verbose_name='Business Plan')),
                ('feasibility_study', models.BooleanField()),
                ('business_templates', models.BooleanField()),
                ('marketing_communication', models.BooleanField(verbose_name='Marketing and Brand Communication')),
                ('social_media_marketing', models.BooleanField(verbose_name='Social media marketing and PR')),
                ('public_speaking_training', models.BooleanField(verbose_name='Pubic speaking training')),
                ('interview_operations', models.BooleanField(verbose_name='Interview preparation training')),
                ('logo_design', models.BooleanField(verbose_name='Logo Design')),
                ('newsletter_subscription', models.BooleanField(verbose_name='Subscribe to newsletter')),
            ],
        ),
        migrations.AddField(
            model_name='meetingexpert',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert.WorkType'),
        ),
        migrations.AddField(
            model_name='expert',
            name='Industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert.Industry'),
        ),
        migrations.AddField(
            model_name='expert',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
