# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name': 'Industry', 'verbose_name_plural': 'Industries'},
        ),
        migrations.RenameField(
            model_name='expert',
            old_name='Industry',
            new_name='industry',
        ),
        migrations.AlterField(
            model_name='address',
            name='Country',
            field=models.ForeignKey(default='156', on_delete=django.db.models.deletion.CASCADE, to='states.Country'),
        ),
        migrations.AlterField(
            model_name='meetingexpert',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
