# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-03 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0002_expert_specify_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
