# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0002_auto_20170821_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expert',
            options={'ordering': ('name',), 'verbose_name': 'Expert', 'verbose_name_plural': 'Experts'},
        ),
        migrations.AlterField(
            model_name='expert',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='expert',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
