# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0003_auto_20170828_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='meetingexpert',
            name='work_type',
            field=models.CharField(choices=[(1, 'Business diagnostics'), (2, 'Operations optimization'), (3, 'Training/HR needs'), (4, 'Business plan'), (5, 'Feasibility studies'), (6, 'Business templates'), (7, ' Marketing and brand communication'), (8, 'Social media marketing and PR'), (9, 'Pubic speaking training'), (10, 'Interview preparation training'), (11, 'Logo design')], max_length=2),
        ),
        migrations.DeleteModel(
            name='WorkType',
        ),
    ]
