# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0005_auto_20171010_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=20, verbose_name='City/Town/Village'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='states.State'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
