# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-25 17:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expert', '0002_auto_20180224_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss', 'Miss'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('Alhaji', 'Alhaji'), ('Chief', 'Chief'), ('Prince', 'Prince'), ('Princess', 'Princess')], max_length=10)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d')),
                ('background_image', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d')),
                ('age_range', models.CharField(blank=True, choices=[('25-30', '25-30 years'), ('31-35', '31-35 years'), ('36-40', '36-40 years'), ('41-50', '41-50 years'), ('51-60', '51-60 years'), ('60+', '60+ years')], max_length=5)),
                ('availability', models.CharField(blank=True, choices=[('daily', 'Daily'), ('forth-nightly', 'Forth-nightly'), ('monthly', 'Monthly')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('short_biography', models.TextField(blank=True)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('cv_file', models.FileField(blank=True, upload_to='uploads/%Y/%m/%d', verbose_name='Attach PDF copy of CV ')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='Link to LinkedIn Bio/profile')),
                ('account_status', models.CharField(choices=[('A', 'Active'), ('D', 'Deleted')], default='A', max_length=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='expert.Industry')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentor',
                'ordering': ('name',),
                'verbose_name_plural': 'Mentors',
            },
        ),
    ]
