# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='account_status',
            field=models.CharField(choices=[('A', 'Active'), ('D', 'Deleted')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='mentor',
            name='years_of_experience',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
