# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-30 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='specify_industry',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='If Others, Specify'),
        ),
    ]
