# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_auto_20170821_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
