# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-03 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_mentor_specify_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='can_migrate',
            field=models.BooleanField(default=True),
        ),
    ]
