# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-02 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_auto_20180225_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
