# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-03 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_mentor_can_migrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='can_migrate',
            field=models.BooleanField(default=False),
        ),
    ]
