# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_auto_20170825_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link to LinkedIn Bio/profile'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
