# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0004_auto_20170825_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
