# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0005_mentor_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='cv_file',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d', verbose_name='Attach PDF copy of CV '),
        ),
    ]
