# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-19 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='sector',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
