# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Country',
                'ordering': ('name',),
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Nigerian Local Government Area',
                'ordering': ('state', 'name'),
                'verbose_name_plural': 'Nigerian Local Government Areas',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Nigerian State',
                'ordering': ('name',),
                'verbose_name_plural': 'Nigerian States',
            },
        ),
        migrations.AddField(
            model_name='lga',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_govt_areas', to='states.State'),
        ),
    ]
