# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentee',
            name='model_of_communication',
        ),
        migrations.AddField(
            model_name='mentee',
            name='mode_details',
            field=models.CharField(max_length=50, null=True, verbose_name='Please give details for the mode chosen above'),
        ),
        migrations.AddField(
            model_name='mentee',
            name='mode_of_communication',
            field=models.CharField(choices=[('whatsapp', 'Whatsapp'), ('email', 'Email'), ('call', 'Phone call'), ('f2f', 'Face-to-Face'), ('skype', 'Skype')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='time_with_mentor',
            field=models.CharField(choices=[('forth-nightly', 'Forth-nightly'), ('monthly', 'Monthy')], max_length=20, verbose_name='How much time would you need from your mentor?'),
        ),
        migrations.DeleteModel(
            name='CommunicationMode',
        ),
    ]
