# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0003_auto_20170821_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='address',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='expert.Address'),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='age_range',
            field=models.CharField(blank=True, choices=[('25-30', '25-30 years'), ('31-35', '31-35 years'), ('36-40', '36-40 years'), ('41-50', '41-50 years'), ('51-60', '51-60 years'), ('60+', '60+ years')], max_length=5),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='industry',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='expert.Industry'),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='level_of_education',
            field=models.CharField(blank=True, choices=[('SSCE', 'SSCE'), ('OND', 'OND'), ('HND', 'HND'), ('BSc and MSc', 'BSc and MSc'), ('PhD', 'PhD')], max_length=7),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='time_with_mentor',
            field=models.CharField(blank=True, choices=[('forth-nightly', 'Forth-nightly'), ('monthly', 'Monthy')], max_length=20, verbose_name='How much time would you need from your mentor?'),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss', 'Miss'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('Alhaji', 'Alhaji'), ('Chief', 'Chief'), ('Prince', 'Prince'), ('Princess', 'Princess')], max_length=10),
        ),
    ]
