# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-06 16:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Displayed name')),
                ('photo', models.ImageField(upload_to='uploads')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Authors',
                'verbose_name': 'Author',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', tinymce.models.HTMLField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', tinymce.models.HTMLField()),
                ('illustration', models.ImageField(blank=True, upload_to='uploads/blogs/')),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(blank=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('publish', models.BooleanField(default=True, help_text='Show this field in the news feed', verbose_name='Publish now')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsroom.Author')),
            ],
            options={
                'verbose_name_plural': 'Entries',
                'verbose_name': 'Entry',
                'ordering': ('-date_created',),
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsroom.Entry'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_commment', to=settings.AUTH_USER_MODEL),
        ),
    ]
