# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0002_auto_20170929_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
