# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0003_auto_20170930_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='illustration',
            field=models.ImageField(blank=True, upload_to='uploads/blogs/'),
        ),
    ]
