# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0004_auto_20170930_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('-date_created',), 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
        migrations.AddField(
            model_name='entry',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
