# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channels',
            options={'ordering': ('-date_created',), 'verbose_name': 'Channel', 'verbose_name_plural': 'Channels'},
        ),
    ]
