# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20170831_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channels',
            options={'ordering': ('date_created',), 'verbose_name': 'Channel', 'verbose_name_plural': 'Channels'},
        ),
        migrations.AlterField(
            model_name='channels',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
