# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-20 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_remove_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='illustration',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
    ]
