# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-20 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_post_illustration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='illustration',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
